### PR TITLE
Fix for encoded bytes and updated build actions

### PR DESCRIPTION
**Pull request by kounch**
- Fix for bad encoded bytes comparing with original source
- macOs build action for universal binary
- Update action versions and fix for Windows build action

### CODE REVIEW

**Comment by stripwax** [comment]
Which particular part is most important for you? Including documentation that is not part of the original source doesn't really make sense to me, and I cannot test anything on MacOS. Whereas the fix does seem useful, but my version seems to work ok without that fix. More testing is required?

It was never my intention to make this a 'living' project in GitHub and I am not the original author; at best, this is a fork. But I can try to help you.

**Comment by kounch** [comment]
Hi. 
I would like to clarify that the added documentation is for the original tool voc2tzx which is the base source. Miguel Angel adapted that source so that it now creates wav files instead of voc, but the rest of the document is still relevant for it’s use

**Comment by kounch** [comment]
The encoded bytes correction is needed so that the compilation works ok with operating systems that do not use classic windows encoding by default. This includes, at least, macOS and some Linux flavours.

**Comment by stripwax** [comment]
Got it, let me check it out later.

**Review by stripwax — APPROVED** [review]
Good catch, I missed this in my previous 714ab6ffdf8dfa6dca9841b828a0b7f86a3f8f0f commit

**Pull request merged**
